### PR TITLE
intern.json

### PR DESCRIPTION
**Pull request by AlonCS**

### CODE REVIEW

**Comment by AlonCS** [comment]
Screenshot 2024-09-22 122003

**Comment by AlonCS** [comment]
image

**Comment by AlonCS** [comment]
image

**Comment by elimanzo** [comment]
Hey @AlonCS. Currently this PR does not follow our [Standards and Practices](https://github.com/BizzNEST/Standards-and-Practices/tree/main/standards), and I recommend taking a look at that before making commits/PRs/ and merges. 

## Merging
This is a pretty big one, we should not be pushing stuff into main without a review from a peer + senior intern. I had to revert the main branch by the commits, and I added rules to `main` so hopefully it won't happen again 😄 

4650543f41ffc53787c57a5decad4763

### Branching
There should be proper branching going off of the doc the template we're using is `<initials>-<issue#>-<small-description>`
Since this was a task in issues it should've been named something like `ac-17-interns-json`

### Commits
Remember we're using [this](https://github.com/BizzNEST/Standards-and-Practices/blob/main/standards/commits.md) as our commit conventions. so it should contain a format like `type(scope):subject`

an example could've been `feat(interns data): Created json file with interns data`

### Pull Request

We are following this [template](https://github.com/BizzNEST/salinas-bizznest-scheduler/blob/main/.github/pull_request_template.md) (which should've been given to you). Try to follow the template as close as possible, if there are things for example you can't show / display then a simple `N/A` can suffice

**I will be closing this PR**, and i'm going to ask you to remake the branch / commits with the proper standards and practices, then we can review them

**Pull request closed without merging**
